### ISSUE TITLE
MBP>"Add" button missing between iACV and $Renewed

### ISSUE THREAD

**Issue by Aditi9Mishra** [MBR-RB360/QA#1]
![Image](https://user-images.githubusercontent.com/125249638/258466636-ef488f10-0724-48ca-86af-30458221121c.png)

**Comment by Aditi9Mishra** [comment]
How it should be:



![Image](https://github.com/MBR-RB360/QA/assets/125249638/6b59507e-dd13-47e0-9546-cdca9d0af980)

**Comment by harrybasra** [comment]
@AshishCopan  Start working on this and, Post the updates here
