### ISSUE TITLE
Default time should be "Quarterly"

### ISSUE THREAD

**Issue by Rishabh8397** [MBR-RB360/QA#4]
![Image](https://github.com/MBR-RB360/QA/assets/141335452/fd9ade2c-a0bd-4934-82cb-0d3cfb1535f0)

**Comment by Aditi9Mishra** [comment]
Should land on "quarterly" for Leader:



![Image](https://github.com/MBR-RB360/QA/assets/125249638/1bf4f695-49e4-4bfe-b207-7822aed953ac)

**Comment by Aditi9Mishra** [comment]
@harrybasra Should be "Deferred", wrong issue, closing the issue
