### ISSUE TITLE
Software 360 > Recurring Software > TCV

### ISSUE THREAD

**Issue by Jyoti25b** [MBR-RB360/QA#41]
The KPIs "Top 5 RSW TCV Offers", "RSW TCV Bookings Split by Business Entity", "	RSW TCV Bookings contribution by Segment" are not being displayed

**Comment by Aditi9Mishra** [comment]
As discussed with Harry sir, this is a frontend issue

**Comment by icopancs** [comment]
UI Id's to be mapped

**Comment by icopancs** [comment]
Added in UI, moving to stage
